application: revercoinapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /code.html
  static_files: code.html
  upload: code.html

- url: /howitworks.html
  static_files: howitworks.html
  upload: howitworks.html

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /js
  static_dir: js
